### PR TITLE
Updating German translation

### PR DESCRIPTION
**Pull request by der-eismann**
There were a lot of typos and misunderstood strings, so I tried to update them all.

### CODE REVIEW

**Comment by der-eismann** [comment]
@ikeydoherty Anything I can do to help you merge it?

**Comment by frnogueira** [comment]
I did send my translations on 27 April... :( I don't know what happen.. No merge!

**Comment by ikeydoherty** [comment]
oh, damn notifications, yay thunderbird notifications though.

**Comment by ikeydoherty** [comment]
(Remember eopkg is no longer actively developed..)

**Comment by frnogueira** [comment]
Great!
When will open translations for solus package? ;)
Ps.: Now, I will finish the eopkg translations. ;)

**Comment by ikeydoherty** [comment]
Translations for packages? Not sure I follow.

**Comment by der-eismann** [comment]
I guess he means translations for sol. Thanks for merging!

**Comment by ikeydoherty** [comment]
Ah right, yeah I've done absolutely no work for sol yet lol

**Comment by frnogueira** [comment]
Sorry.. sol ;)
Thanks!

**Pull request merged**
